[all]
minio ansible_host=192.168.86.215

[containers]
minio

[minio]
minio

[all:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3.13
minio_root_user=rene
minio_root_password=ma:de3108
