name: Local Assistant
version: 1.0.0
schema: v1
models:
  - name: qwen2.5-coder 1.5b
    provider: ollama
    model: qwen2.5-coder:1.5b
    roles:
      - apply
      - autocomplete
      - chat
      - edit
  - name: gemma 4 latest 
    provider: ollama
    model: gemma4:latest
    roles:
      - apply
      - chat
      - edit
    capabilities:
      - tool_use          
  - name: Fast Apply 1.5B v1.0
    provider: ollama
    apiBase: http://localhost:11434
    model: hf.co/bartowski/FastApply-1.5B-v1.0-GGUF:latest
    roles:
      - apply
    defaultCompletionOptions:
      contextLength: 32768 
  - name: nomic-embed-text latest
    provider: ollama
    apiBase: http://localhost:11434
    model: nomic-embed-text:latest
    roles:
      - embed
  - name: Qwen3-Reranker-4B latest
    provider: ollama
    apiBase: http://localhost:11434
    model: hf.co/QuantFactory/Qwen3-Reranker-4B-GGUF:latest
    roles:
      - rerank
