[all]
grafana ansible_host=192.168.86.101
prometheus ansible_host=192.168.86.151

[containers]
prometheus
grafana

[prometheus]
prometheus

[grafana]
grafana

[all:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3.13
prometheus_ip=192.168.86.151
grafana_ip=192.168.86.101
