[all]
open-webui ansible_host=192.168.86.64
searxng ansible_host=192.168.86.60

[containers]
open-webui
searxng

[open-webui]
open-webui

[searxng]
searxng

[all:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3.13
ollama_host=https://ollama.grumples.home
