---
- name: Prepare all containers
  hosts: containers
  become: yes
  roles:
    - docker_host_base

- name: Deploy Prometheus
  hosts: prometheus
  become: yes
  tasks:
    - name: Ensure prometheus directory exists
      ansible.builtin.file:
        path: ~/prometheus/
        state: directory
    - name: Copy prometheus.yml file
      template:
        src: prometheus/prometheus.yml.j2
        dest: ~/prometheus/prometheus.yml
        #we scip the copy if existing on server
        force: no
    - name: Run prometheus container
      community.docker.docker_container:
        name: prometheus
        image: prom/prometheus:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "9090:9090"
        volumes:
          - ~/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro

- name: Deploy Grafana
  hosts: grafana
  become: yes
  tasks:
    - name: Ensure Grafana provisioning directory exists
      ansible.builtin.file:
        path: ~/grafana/provisioning/datasources
        state: directory

    - name: Copy datasource provisioning config
      template:
        src: grafana/datasources.yml.j2
        dest: ~/grafana/provisioning/datasources/datasources.yml

    - name: Run Grafana container
      community.docker.docker_container:
        name: grafana
        image: grafana/grafana:latest
        state: started
        restart_policy: unless-stopped
        ports:
          - "80:3000"
        volumes:
          - grafana-data:/var/lib/grafana
          - ~/grafana/provisioning:/etc/grafana/provisioning:ro
